server:
  port: 8090
spring:
  data:
    mongodb:
#      username: leo
#      password: 123
#      host: localhost
#      port: 27017
#      authentication-database: admin
      database: customer
#      uri: mongodb://leo:123@localhost:27017/customer?authSource=admin&authMechanism=SCRAM-SHA-1
