spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service
#  data:
#    mongodb:
#      uri: mongodb://leo:123@localhost:27017/customer?authSource=admin&authMechanism=SCRAM-SHA-1
#      database: customer


